### ISSUE TITLE
环境一定要python 3.0吗

### ISSUE THREAD

**Issue by remberi** [SmallRuralDog/auto-login-alimama#2]
我用python2.7 run的时候报
Traceback (most recent call last):
  File "alimama.py", line 76, in <module>
    sp = Spider()
  File "alimama.py", line 11, in __init__
    self.web = webdriver.Chrome()
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)

**Comment by yuanzhizhu** [comment]
没有装相应库吧

**Comment by SmallRuralDog** [comment]
只要用到的库支持2.7就可以用2.7
